import localFont from "next/font/local";
import "./globals.css";

const instrumentSans = localFont({
  src: "./fonts/InstrumentSans-VariableFont_wdth,wght.ttf",
  variable: "--font-instrument-sans",
  weight: "100 900",
});
const instrumentItalic = localFont({
  src: "./fonts/InstrumentSans-Italic-VariableFont_wdth,wght.ttf",
  variable: "--font-instrument-italic",
  weight: "100 900",
});

export const metadata = {
  title: "dev-links",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${instrumentItalic.variable} ${instrumentSans.variable} antialiased bg-bg-light`}
      >
        {children}
      </body>
    </html>
  );
}
