import localFont from "next/font/local";
import "./globals.css";
import { LinksProvider } from "./_components/useLinkContext";
import Navigation from "./_components/Navigation";
import Container from "./_components/Container";
import PhoneAside from "./_components/PhoneAside";
import { cookies } from "next/headers"; // To access cookies server-side

const instrumentSans = localFont({
  src: "./fonts/InstrumentSans-VariableFont_wdth,wght.ttf",
  variable: "--font-instrument-sans",
  weight: "100 900",
});
const instrumentItalic = localFont({
  src: "./fonts/InstrumentSans-Italic-VariableFont_wdth,wght.ttf",
  variable: "--font-instrument-italic",
  weight: "100 900",
});

export const metadata = {
  title: "dev-links",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // If the user is authenticated, render the full layout
  return (
    <html lang="en">
      <body
        className={`${instrumentItalic.variable} ${instrumentSans.variable} antialiased bg-bg-light`}
      >
        <LinksProvider>
          <Container>
            <>
              <main className="flex flex-col gap-4 mt-4 md:flex-row">
                {children}
              </main>
            </>
          </Container>
        </LinksProvider>
      </body>
    </html>
  );
}
